# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: mayyinandprojects
# "service" is the name of this project. This will also be added to your AWS resource names.
service: auth-server

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  timeout: 30 # optional, in seconds, default is 6
  environment:
    CLIENT_ID: ${file(./new-item config.json):CLIENT_ID}
    CLIENT_SECRET: ${file(./new-item config.json):CLIENT_SECRET}
    CALENDAR_ID: ${file(./new-item config.json):CALENDAR_ID}
functions:
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - http:
          path: api/get-auth-url
          method: get




#default template provided by serverless.yml:
# functions:
#   hello:
#     handler: handler.hello
#     events:
#       - httpApi:
#           path: /
#           method: get
